sudo: required
dist: trusty
language: node_js
node_js:
- stable
branches:
  except:
  - gh-pages
before_script:
- npm install bower
- export PATH=$PWD/node_modules/.bin:$PATH
- bower install
script:
- echo "No tests for demos"
after_success:
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then openssl aes-256-cbc -k "$DEPLOYSECRET"
  -in deploy.enc -out deploy_key -d; fi
- cd $TRAVIS_BUILD_DIR/scripts
- chmod 755 ghp.sh
- "./ghp.sh"
env:
  global:
  - secure: gbnmnjYKmOuFA6cVZUGtfDYW62yn0MC7ePlmy2+nk9g37OUq/CKhk9oElshVd1fR0o6Q3ke8fO9UaU80sb86HIzj0ln+ZsiUFsDf716Zn65WTQyxEIcp8bKOy9SBy9hrdvx36WDK8OwvxsuQGQx1JoRxFp2UrYRKO7JOM4tCe/AydsynTY2Ptgx0N9q/RNNhi4Mx+HtwNTPGGs0CQYn1+eTIvtz3ya3p0X5q68PXV6cO4pqxbWlHsHL9hHu/8FXkfLsSsrHby7pmdXX2D+oVFIGeV2/Jlc9RG8V3+olfLwnsCQ1JupzKzaA6fXC3CXEeg5wQ9qD+2w1IT2WPFrR7k/OWIt9hJs8C+EowvNMxok2ADrTkYsfXTN46MdPDwlEMkSJEIcvhXPov7d9YtSp5tdfy4Tq8f2q4LFkXK1H0mahTdzKxsyNekRVb9PDjppm+OaT3xRfBPkrGZglopeOHciR7O/+81nEsxFmUVLT+2KE6ERV5BbdKueOlja6krX3blzbyjTnSpUMXx/EWe0IZqMsgVRr3sZrRcYs7Qvkbp6ppFXyK3cHN5vV4rgHL3JasaEwFOh9NwciV7YTN65xPkNYOji+H8prlDjYICUQdIqmz1lMDrjOgoHNDw4topQ3Ni+6fSfkPbnfOgCEa8hrKL9ITJjZvHHHrxvvkjUTSvdU=
  - secure: NqaBVs/EefMSftQK9FEdj+sIqonZxAYemVJ2ay8BTm4oekL3ECIP/1lxSzGV7Cz0vQJpi7Ih7wStz3/HQxc0n8ZosH1S3puaH3Hkxa8v6uh1zAVlHZ5/tfwLz9n0aLzVBas7K5bOtSX0GOJ8qLCuko+htKx1viBocj7T9oVNHB6RkW60kD0VYn5uIdzQPuWYhTtniUky/VmkaEzoX5PL9ZneRDV8NunL8KCvOxatOYWZsAzWDt5fkFmjz7fPE9TpTihuyTi4TIm4+utiiJ3IYLHGRZn/97oQl3rPj6WIctfGFWhwpLfJEkxsQIpi4tdeWUVeq5reDT8Qjs/cpl7uoKnet6+WgxFEG6lvwPQSQjGIqpTfalrK1ONsakhvdlW03gf0W1I0VV5seiC4tTaKY9OJu0u5MKvv9gLJhsUBTsrNua0yf1HPTTMZ7k3hnaBKbl21iL2YQErUL92bwqbqnCmBmNEC8w3uUhL080YSjfF3VZTcU5xTnzv+ayupu5ZE1V290E+LXe1434sD9F8ajDVlH817WFhj38lOqVIDuHvzbU09Vswp4SXxSAorlt2gAisb1+MXgyfA0Ot8+AjRdLxBeXbnHzODUeL9lJWQeDxpb0MEX8hJZxx5706eJg3vGX8IqREQowbgDJbPOkTggf7Sjkix/adkgzkN/lTtwFM=
  - secure: S3wuTpOMsXEBLli1AA7dJeqtFZk+Rwnt01wS6XkfsigKHXPKfwsz+LpfwCkT67UnSnNaIzG47LLugmBBKbldg34elcrntTeFwh/ptUU04O8SxX3xb0BAL5Yz6bg50mZzhnV47rqTWGBZRoq1mQLzcbUeywCIrugLQw8zwRAIFYic+OfoQ4uEP08HrHRnyltP3mQNEakP1gwNkH3dD++tPd2FXphMhdPP4hco7n19dCLZvTNMrluh8GApsiUxhiA3lm5486jyco22vcsACnCfmaB48bFWmJOedPlnp1W4olL+OLUgUmJ2CxtLuFHCusvmAgSj7fU0WJz41WDi1SHDbEN51xGUCO0DprPIPxzw48uKIk/txNvCnRvG3PSI4t+TaAWQxPyobHwX83fn2ibkl5mvR+48BqOhJBYm8FQ7jn5+IJX/8+7JhOYO8oFJL1CBa21Kp7Kh/XGejXnHIStc/fw44JQ7x138GV+3kAVaS2+Arldga/bz6tzvFZjye8Ml6B8Mh3CjrTgssyXNYotCOo7q7O/3+s3h9kR6Rp62VPq5Vusyze6SMwjiUWgw1HNyYLGCx2UNzfqXr9w1y7DZLnJsq+ySOW8jI5un259wMANeEDKTp0F/a5Z9HmTZgxyFABGrDE9/sEo0mMlZI35c7DL9yEZo/5jkBkRpamG9uto=
  - secure: ZIoIddxZgykdENMfZSvTBeiCskT7Fo65WtMJHHVtw7jRZp8ALVvR/swl9Qy4UKlvj/DvMezFrnfrfuOMbSRNF/QA5C9piPxbmYEdlrogB5gwN4Pwp26CE5t8oveECaTLkbERWCOacoHn63p4FfWp0oip0q4DiR8Ynr8FWT1XNPkHA7qhyAqAvyRk1V7Jv1cWLydWUbfI2JV7I0oX5oazXMZT85lckLt5c0aRkZMx2jn+A0CIPbLqcRiGhGDnsBUs35FoqdAiun0JbNeTWNwKBeBQn9wdxYzP1ZH0VusMeBkK+ANMTTGdlIe0bqjLb3toqs9pC86qC/GCb+xVX48fRsAFsa+C5+1v6zJIrACzCtoRv70Wec9YM7f03MJIKvhOWl13pMeoD4WQoRr0gLJm1d/bT7QSwBXzA4Gy1PG4VYBMsbD5G+mwvvLQav3vMLCUdRknUphP+GroXaReJKo0AX8GJKoTtYDFp/n6SLMkVmmTPTsVDOdijWdNX42Mxk1rs9wDAvIUCbOeiTDFeuuRinJ1ElhVV6t5bUDh9jgnHXBRNVGsBBcCgUJQvOYW+T0l7lJ7DPX0b7TxfozTHCunY+tR6Fxh6fRVJVV1+dZHKntNqvCEuu2MI5Vzyg8QIguVP5bJVHvfH0S+zay+26QAhFMsPWJWU6Pmza74V2B97Fg=
