sudo: required
dist: trusty
language: node_js
node_js:
- stable
branches:
  except:
  - gh-pages
addons:
  firefox: latest
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
before_script:
- npm install web-component-tester
- npm install bower
- export PATH=$PWD/node_modules/.bin:$PATH
- bower install
script:
- xvfb-run wct --skip-plugin sauce
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then wct --plugin sauce --skip-plugin
  local; fi
before_install:
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then openssl aes-256-cbc -k "$password"
  -in id_rsa.enc -out deploy_key -d; fi
after_success:
- cd $TRAVIS_BUILD_DIR/scripts
- chmod 755 ghp.sh
- "./ghp.sh"
env:
  global:
  - secure: mXQKvoz5+uVFNk7IApB57AupvZY2Qp3dguwRAwvDo8al40UQv5mC/h2eHJZZDXKwkvkHE67wkq93dkTdUq3u86yPiMTL37JN5W95lUdw2PD6H7UKTF7FTIn7aELQcj8fZ4bKup1bKrjkCQFeD080Pk/p4EYA9P4Aylkmj+/2lU3sKP21sGzgIdm9640LPplzkbDgkFXCTC1cVG9tyLT1WdE0PLZFYbyETCwkZaSLDvZmz/htFjygxBJ+t2x/YRQj89x5/Yb3zM/SE6CqwhwGwh6k3/ugXM/I1eRkbP0AfNyjhGPLaDBlh4rFwLZvIVuOI7mLFdQJYxVnkVLLPXMcZeLyXA4yZHjPOmsTaZnnP+GKSyG3NYkSgOwwTXLEZdsjzpW6QQnftyHWW9BmqDL78RTadQH/2QkQrvy4ga42N1dWKjuiUdY17IkNyh+qwVIKdgNfEHUDPbORb4luXgNPCvz8xHQHsZExSxIUP0Qztatu5i1lLbeh3DZW/4Dq4LWUTAO8/QSp6XxBbXe6wrlAMxc09JrX/HjVf+Qe78pVyQjF9Tu36DM5ElwD3Si5jhoBXX356tHvw4P5aR1+n9sKEuYhCamYk13Ca+Bf+4nxDxb2nbb+y58DbHvs8lZgvtn+mIcEGy9Blh3NImI/oDUjBhUeyYFHtDOe0fD7GKCNuZU=
  - secure: Fjfy+YPlfB+vGFxP0ffIS1vqLXFK6nYVj4RGdnyn3NxX4F9Jrw+k1cNaz4+ugDguubPyN/8AQMvPnZ+z5Z6IsPEoDREOfm4hi9Zl0w2E/4RYS5yhWtZArSUg/VdkBeUM30RztkXvXBN3PaUEq6MmxbCwaipZldJsgmzItXS7YWEylIKpcjHcLLsaHQqJC+O7tLrU7ik8Q+dGdBTj0GTZLFOSJl9OJYsl7RXSa9jaquCpiZYnLbZZpS/Kt7fA/7NJwaTJVJOEVDyOOdt24B8QQT4gu79ZULmmU6GEdnRTDS4rYAPtPbZLrYFTDc/y1YLv0uqqKtlGg0MHJb4uFMC1W1F6ezqPvEZqv0tLPyfAwJ3ZXhvj9TcPky/tYe72Oqs9N6nr9eydw8yoJ0yAWUiWE8M3QNczpJv06sbNsFCwaxY+RFlS+V+cQp/JKm6wd0QX6VgKnSS9MGw6h4zRdh77u5LZb0AS0twPA71XmjFydWE/n2nDMLybJoSAmFjf0InxdjaZ9bjcjeO31IQcerDPxYAEi80pFS8mvd06NhZba9Hhz8nLGGXckHvOZSd87H0ErFkgrQYTTxK/mcgMqWak/1i0fecHrVWz/vStFQAzKt67MGXrp7BjJhKe5Hy+Q1WuquWHgWXSEBfQtu4aQWW65DiwUV2BUIAgrrWgLsFksdg=
  - secure: LDuRY6bBSpMuhkvh448WrVPIS/hE/5I3omKjl0u7QiyPeZ9ae5h+8wKrljslMWcj4xxGf1e8wVBlcpmINtBUMuyCqQu2Dv/4/6daMkkZZAoOjH598CQZ5yI6Sxd/1t/1LWSepozfR1SRDSN3bhN5zW/WaBo8oazu8Lecf7EiNvhL5yBozOnia11TM6bchQAEMwqGPTOPDuwi2Ts7+sDv4wT1jHJELLaG+CJBzVQ696XTaGEcHIVsBXvH5Te2ao0qK7mYo9ZtCaMUuio4sUPDIyUko/XanM49OEHBWP1yuzm2h/qQSf33XDtwhJ6bryh+rkIQ2DmrxjUuAzGovCuAXO0XJa1yuF+0P6/5aNEajig9QurKTmuFMUcHWiaLcFh00HEPLZcpHq6mQrH1UQvKO5IFifxbQLi6Pz8PsQFbUDGGlJBqnmnY4Jek1shhWGNTg3kwEja+jc7aPdqvntyLkCp4ALEFMmd0O1e08agUVl8XJdPPKjYjoUXpKC0idJdXFqWz2uc0L88k2970/ZlUuAe/fkMApnbHv3sSPUR+iCqL7IslOfMqE6A5n5vxIT9IKE3ckuPckphMiQ+Y7fVN64QmA0B/fBaK0FDInYIjuo0uDNYfvXmU6FLDSLP63vB7UrVQUKVaYBsjohg+2ltMRV6ZcIejiWgXDyrhuybtOck=
  - secure: nxLeQJ/CD3IWPCTUS3B2kj06IAFuXTap3WbIJ1y7OYXhnU4g4FgXnDeAZGYrAF0VU3e7YJB0++Y3gbs39GLhOpmFWyFgHfIJ/ClSCMjboANCSLPOLid54pfLerOfXJ8Fx+7+vtrdukvxMp9XoVqdDfmQCt/YF3o8YU8Vy8MtFzyiTQTVf+tbkHIjwnoqQ+9re0GWtJP977dyZCNDFTmjtFKFlzCRh9C5Ls3OaVVJOicXIntTToEXknR/m6v6cWYaRp9txi0/ij8Si9EzbJAkeTkYF5L75W9t020wFa/0KYZkVfJ2asg2fRKNHjuZcKp9TvZ1z9Wl0TXMESgtjHNJ3lW+sVG3Cs66SzwysVm447mXxN1yy9VlXF5IkIz/GnEdnsHPndMhXR06XmZ90IwPhy+86+GvRFG/hRfUXHd9AUvF2NkzLWsucyDDHZQGTYvp3gZ5zYbMOQOKehaalZQo9p/vcBBSlPcS7BjAk7IK3LL+lE9wCi6coQtBhqFwKUcWS11mY7kdYXLpfpDN1lNyfvHdejL6P0zJCQmmNBbfqK8nyEuO95kwO40qSAm7509IVOpwAHcK0pp3eylJdzDdNjeO6VkIPC96ZXl2rTCoMRMm4548n5qF/3ytns9GlxopK96b/I5guRWWtg2ZMRRnANt+1MDiPPSXuB1XNNoAudU=
